### ISSUE TITLE
How to find the OCID API key?

### ISSUE THREAD

**Issue by Gustav1** [CellularPrivacy/Android-IMSI-Catcher-Detector#182]
Version: 0.1.24-alpha on Acer Liquid Z200

Dear AIMSICD team,

I installed your app of the IMSI Catcher Detector on My Acer Liquid z200. As far as I can see it works. Thanks you for making this app! I like to use the map viewer, but I don't understand a word of all this computer language. 
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Installation On this installation page, you said go to the OpenCellID website, which I did, but I don't know how to find, or even what it is, the so called OCID API KEY. I sent an e-mail to Markus from the website OpenCellID:

> Dear sir,
> 
> I installed AIMSICD on my android device and I want to see the location of all cells on the map.
> In the preferences I have to give my OpenCellID API Key, but this stuff is so hardcore difficult for me, I really do not understand how to get this key, or where to find, or to look, or even what it is. I know nothing about computer language. Can you help me please?
> 
> I couldn't find some decent information, understandable for me, on their own website and their comments-forum (on github).
> 
> I try to find for more then 2 hours, so I hope you can help me.
> 
> Gustav

His response:

> Hi Gustav, 
> 
> what would be the benefit for OpenCellID if we would open your API key? 
> 
> Please ask the aimsicd team to add a proper information how to retrieve an OpenCellID API key to their software. We cannot take over the support role for their software. 
> 
> Cheers Markus
> OpenCellID Ambassador

So I really hope someone can tell me how to retrieve this key (in normal english please :D)
Thanks, Gustav.

**Comment by Gustav1** [comment]
Sir,

I have a new phone, and a new simcard/phnenumber.

I see that your app has been changed slightly.
How can I get this great app working again?
The app icon is yellow and gives me the following message: Cell ID does not exist in OpenCellID Database!

I already sent some debugging logs, but no response yet.

In the app, I clicked on "preferences" and "Request OCID API Key"
I received this key (says the message) so I suppose I don't have to save it again under the button "OpenCellID API Key"? (I assume this autiomatically happens.) 
Then I can't find "contribute cell data" anymore.
I clicked also on both options, "Download Local BTS Data" and "Upload Local BTS Data", which gave me a succeed message. But the Icon is still yellow and with the same message.

Let me know something,
Gustav

**Comment by darkerego** [comment]
Hey Gustav,
I'm not one of the developers, but I do actively follow this project and perhaps can help you. In the later releases, you can request an API right from the app, once every 24 hours, and yes it automatically saved for you. I've also noticed the option in the preferances to contribute data is no longer present, however as you mentioned, you can manually upload the data. Although I am not sure what the reason for that change is, I do think it is a good idea because it allows me to connect to a secure server (such as a VPN or socks proxy) before uploading my measurements, giving me some protection from potential snooping over the insecure GSM/WCDMA data channels.
 
I also seem to get the yellow 'Cell not found in OCID db' warning much more frequently since updating. I believe this is something that the developers are looking into, although it may also be a legitimate warning. I also run SnoopSnitch, and have received quite a few ISMI catcher & silent sms alerts in my service area, so something very well may be amiss and the app is doing what it is supposed to. I will upload debug logs soon too, as I am curious. I hope I was able to answer some of your questions.

**Comment by SecUpwN** [comment]
@Gustav1, thanks for getting back to us on this. If you would have compiled the code from our `development` branch, you'd have noticed that this option to retrieve the OCID key has been removed for now since we want to ensure that our app is not uploading fake CIDs of IMSI-Catchers into the OCID DB, which would in turn mess up the OCID databases for everyone. The CIDs in your area are not yet to be found in the OCID DB - and that is exactly teh reason why AIMSICD keeps showing the yellow warning. We're currently evaluating a work-around, but until this has been fixed you should make sure to contribute to the OCID DB with another app, which will enhance the OICID DB for everyone.
