### ISSUE TITLE
Rant about project ALPHA status and false positives

### ISSUE THREAD

**Issue by CunningLogic** [CellularPrivacy/Android-IMSI-Catcher-Detector#832]
Sorry i lied on the subject, just to get attention. 

SecUpwN refuses to stop spamming myself, my co-workers and other associates. Email, XDA PM, IRC whatever, he always does it. It has been going on for years. No professional wants to work on this project because of him, and the fact that it is by design a deaend, and those leading the pack are unprofessional and childish.

It does not work on modern IMSI catchers, it doesnt detect them, it also loves to set off and give false positives. Did you know there is an IMSI Catcher on the etihad flight from Dallas to Abu Dhabi? Well there isn't, its just a regular tmobile basestation, and authentic one, but this broken app still thinks it is.

So, when I get back to the US, I'm going to use whatever swing left I have at XDA and take down related threads, and if possible deal with related contributors accounts. 

Grow up guys.

**Comment by SecUpwN** [comment]
@CunningLogic, I am sorry for having forgotten that you were in fact the one who was fed up with our project back then already when it was still active on XDA (it isn't, for the exact same attitude of people you're sadly showing here). Furthermore I feel that it was a big mistake of mine to contact you again with an invitation to our team. I thought you may have been a useful addition after your wonderful work with the `SunShine` root development. But since all you say is that our **ALPHA** app (hence it has so many bugs, you should know that best as a developer) is a "piece of shit" and I "suck at managing the project", I will cease to contact you with anything in the furure.

Since your attitide towards our project hurts our [Code of Conduct](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#code-of-conduct), I sadly have to expell you from the team and enforce this conduct by blocking you from our GitHub account. Congratulations, you're the first I need to enforce this policy upon. In fact, this does not feel good at all since I truly value your work on XDA and everything you've given back to the Android community. But I really do not understand your behavior here in public. It raises the question who *really* needs to grow up. Rest in peace, Jcase.
