### ISSUE TITLE
"current threat level" shows me neighouring cells, not threat level

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#848]

**Comment by agilob** [comment]
Is anyone doing any kind of user testing before changes are released?

**Comment by SecUpwN** [comment]
>Is anyone doing any kind of user testing before changes are released?

No, we simply refuse to test anything tpo collect even more bugs! /sarcasm Of course we're testing a large number of things before releasing it into the wild. But since our `ALPHA` app is a community effort, we rely on the feedback of users until we implemented #173. Feel invited to help us there! @He3556, shall we close this Issue as `INVALID` (since that tab is not fully implemented yet) or really rename the tab to say `Neighbourings Cells` instead? Would like to hear @larsgrefer and @mimi89999 as well.

**Comment by mimi89999** [comment]
Maybe we should implement this tab?

**Comment by SecUpwN** [comment]
>Maybe we should implement this tab?

We could just rename `Current Threat Level` to `Nighboring Cells`, then it would be correct again.
I'd like @He3556 to state his opinion here and then I'll tackle this as soon as possible.
