### ISSUE TITLE
Unable to scroll up in neigbouring cells view

### ISSUE THREAD

**Issue by agilob** [CellularPrivacy/Android-IMSI-Catcher-Detector#876]
1. Scroll down  neighbouring cells list
2. Try scrolling up
3. View is refreshed

**Comment by SecUpwN** [comment]
@CellularPrivacy/design and @kaichunlin, please have a closer look at how this may be fixable.

**Comment by kaichunlin** [comment]
@SecUpwN @CellularPrivacy/design The problem is that an unsupported layout(`RelativeLayout`) is used within `android.support.v4.widget.SwipeRefreshLayout`

To fix this issue, I will make a non-generic version of `com.secupwn.aimsicd.adapters.BaseInflaterAdapter` such that what's currently being wrapped in the `RelativeLayout` will be replaced with a single `ListView`, and the first item of the `ListView` will contain the _Neighboring Cells/Total_ info.
